import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AuthProvider from "../context/AuthProvider";
import { Toaster } from "@/components/ui/sonner";
import Navbar from "@/components/navbar/Navbar";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "nextjs-project-1",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark" >

      {/* on continuation to the file made in context/AuthProvider.tsx */}
      {/* ${geistSans.variable} ${geistMono.variable} --> agar ye missing hue to font-sans, font-serif etc kuch apply nhi hoga pages pe */} 
        <body className={`min-h-full flex flex-col bg-i-black ${geistSans.variable}
          ${geistMono.variable}`} >
          <AuthProvider> 
            <Navbar></Navbar>
            {children}
          <Toaster />
          </AuthProvider>
        </body>
      
    </html>
  );
}
